spring:
  application:
    name: framework

  datasource:
    url: jdbc:postgresql://localhost:5432/task_manager
    username: user
    password: password
  jpa:
    hibernate:
      ddl-auto: update

server:
  port: 9999